server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Wangyanjunai/spring-cloud-config-repo.git # 配置Git仓库的地址
          username: '***151***@qq.com'                                     # Git仓库的账号
          password: '***123***'                                            # Git仓库的密码
          repos:
            team-a:
              pattern:  microservice-*
              clone-on-start: true
              uri: https://github.com/Wangyanjunai/spring-cloud-config-repo.git
              username: '***151***@qq.com'                                        # Git仓库的账号
              password: '***wj2***'                                            # Git仓库的密码
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG          