server:
  port: 8040
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/            
spring: 
  application:
    name: microservice-gateway-zuul-filter
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always    