server:
  #指定tomcat端口
  port: 8001
spring:
  jpa:
    #让hibernate打印执行的sql
    show-sql: true
  application:
    #指定注册到eureka server上的服务名称，对于电影微服务，本系列将名称设为microservice-consumer-movie
    name: microservice-provider-user
logging:
  level:
    root: INFO
    #配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
management:
  endpoint:
    health:
      #展示显示健康详情
      show-details: always  
  endpoints:
    web:
      exposure:
        #如需暴露所有监控端点可配置 *
        include: '*' 
eureka:
  client:
    service-url:
      #指定eureka server通信地址，注意/eureka/小尾巴不能少
      default-zone: http://localhost:8761/eureka/
  instance:
    #是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
