server:
  port: 8080
spring:
  application:
    name: microservice-config-server-encryption
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Wangyanjunai/spring-cloud-config-repo.git # 配置Git仓库的地址
          username:                                      # Git仓库的账号
          password:                                      # Git仓库的密码
#logging:
#  level:
#    org.springframework.cloud: DEBUG
#    org.springframework.boot: DEBUG