server:
#  指定tomcat端口
  port: 8000
spring:
  jpa:
#    让hibernate打印执行的sql
    show-sql: true
logging:
  level:
    root: INFO
#    配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
