server:
  port: 8010
management:
  endpoints:
    web:
      exposure:
        #如需暴露所有监控端点可配置*
        include: '*' 
  endpoint:  
    health:
      #展示显示健康详情
      show-details: always
spring:
  application:
    #指定注册到eureka server上的服务名称，对于电影微服务，本系列将名称设为microservice-consumer-movie
    name: microservice-consumer-movie
eureka:
  instance:
    #   是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
  client:
    service-url:
      #   指定eureka server通信地址，注意/eureka/小尾巴不能少
      default-zone: http://localhost:8761/eureka/
feign:
  hystrix:
    #   加配置，默认Feign是不启用Hystrix的，需要添加如下配置启用Hystrix，这样所有的Feign Client都会受到Hystrix保护
    enabled: true     