server:
  port: 8080
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Wangyanjunai/spring-cloud-config-repo.git #配置Github仓库的地址
          username:                                                         #Github仓库的账号
          password:                                                         #Github仓库的密码
eureka:  client:    service-url:      default-zone: http://localhost:8761/eureka/                     