server:
  #指定tomcat端口
  port: 8000
spring:
  jpa:
    #让hibernate打印执行的SQL语句
    show-sql: true
  application:
    #指定注册到eureka server上的服务名称，对于电影微服务，本系列将名称设为microservice-consumer-movie
    name: microservice-provider-user
  zipkin:    base-url: http://localhost:9411
  sleuth:    sampler:
      #采样率，模式0.1，也就是10%，为了便于观察效果，改为1.0，也就是100%。生产环境建议保持默认。
      probability: 1.0    
logging:
  level:
    root: INFO
    #配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    #hibernate打印出执行注入的SQL参数
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #hibernate打印出获取到的SQL值
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    #打印更多Sleuth相关的日志
    org.springframework.cloud.sleuth: DEBUG                
management:
  endpoint:
    health:
      #展示显示健康详情
      show-details: always  
  endpoints:
    web:
      exposure:
        #如需暴露所有监控端点可配置 *
        include: '*' 
eureka:
  client:
    service-url:
      #指定eureka server通信地址，注意/eureka/小尾巴不能少
      default-zone: http://localhost:8761/eureka/
  instance:
    #是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
