server:
  #  指定tomcat端口
  port: 8000
spring:
  application:    name: microservice-simple-provider-user
  jpa:
    #让hibernate打印执行的sql
    show-sql: true
  zipkin:    base-url: http://localhost:9411
  sleuth:    sampler:      probability: 1.0
logging:
  level:
    root: INFO
    #配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.cloud.sleuth: DEBUG
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
management:
  endpoints:
    web:
      exposure:
        #如需暴露所有监控端点可配置 *
        include: '*' 
  endpoint:     
    health:
      #展示显示健康详情
      show-details: always
