server:
  port: 8761
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    #是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    #是否要注册到其他Eureka Server实例
    register-with-eureka: false
spring:  security:    user:      name: user
      password: 123456      
